### ISSUE TITLE
component doesn't react if selected value is changed from code

### ISSUE THREAD

**Issue by kot-pilot** [nathanboktae/knockout-choose#4]
component doesn't react if selected value is changed from code :(

**Comment by nathanboktae** [comment]
[Yes it does](https://codepen.io/nathanboktae/pen/WOOLEB?editors=1010#0) and [there are tests for it too](https://github.com/nathanboktae/knockout-choose/blob/master/tests/tests.js#L442-L453).

If you're using `knockout-es5` or `knockout-es5-option4`, if the selected is behind a property, you need to make sure you set the value on the original object. e.g.
```javascript
viewModel.selected = 'foo' // invokes property setter, which is wired up to knockout
```
 not
```javascript
var selected = viewModel.selected // invokes getter which gets observable value
selected = 'foo'; // only reassigns your local variable.
```

**Comment by kot-pilot** [comment]
does it work with dynamically changing options?

**Comment by nathanboktae** [comment]
Sure as long as an option is triple equals equivalent to something in the
options.

Update the codepen with a repro of your scenario?
